#include "VectorSuiteCatalog.h"
#include "VectorSuiteID.h"

const VSModuleDefinition kVSModules[kVSModuleCount] = {
	{kVSPrecisionPen, "precision-pen", "Precision Pen", "Disegno",
	 "Creazione precisa e modifica controllata dei tracciati.", 24000},
	{kVSFluidSketch, "fluid-sketch", "Fluid Sketch", "Disegno",
	 "Disegno vettoriale naturale con mouse o penna.", 24001},
	{kVSInkStudio, "ink-studio", "Ink Studio", "Disegno",
	 "Tratti calligrafici e simulazione dell’inchiostro.", 24002},
	{kVSWidthStudio, "width-studio", "Width Studio", "Disegno",
	 "Controllo dei profili di larghezza e delle tracce.", 24003},
	{kVSPathStudio, "path-studio", "Path Studio", "Geometria",
	 "Costruzione, pulizia e modifica intelligente delle forme.", 24004},
	{kVSGeometryLab, "geometry-lab", "Geometry Lab", "Geometria",
	 "Costruzioni geometriche, tangenti e allineamenti.", 24005},
	{kVSCollisionAlign, "collision-align", "Collision Align", "Geometria",
	 "Posizionamento e allineamento tramite collisioni.", 24006},
	{kVSMirrorStudio, "mirror-studio", "Mirror Studio", "Geometria",
	 "Simmetria radiale e speculare controllata sul canvas.", 24007},
	{kVSShapeReform, "shape-reform", "Shape Reform", "Geometria",
	 "Rimodellazione diretta della grafica vettoriale.", 24008},
	{kVSLiveStyle, "live-style", "Live Style", "Aspetto",
	 "Controllo visuale degli effetti e dell’aspetto.", 24009},
	{kVSColorLab, "color-lab", "Color Lab", "Aspetto",
	 "Correzione del colore e trasformazioni tonali.", 24010},
	{kVSTextureLab, "texture-lab", "Texture Lab", "Aspetto",
	 "Texture vettoriali controllabili e ripetibili.", 24011},
	{kVSStippleLab, "stipple-lab", "Stipple Lab", "Aspetto",
	 "Puntinatura e simboli distribuiti in modo parametrico.", 24012},
	{kVSRandomize, "randomize", "Randomize", "Aspetto",
	 "Variazioni controllate di posizione, scala e rotazione.", 24013},
	{kVSSmartFind, "smart-find", "Smart Find", "Workflow",
	 "Ricerca e selezione di oggetti per attributi.", 24014},
	{kVSVectorRepair, "vector-repair", "Vector Repair", "Workflow",
	 "Diagnosi, semplificazione e pulizia dei documenti.", 24015},
	{kVSRasterLab, "raster-lab", "Raster Lab", "Workflow",
	 "Controllo e gestione delle immagini raster.", 24016},
	{kVSAutoSave, "auto-save", "Auto Save", "Workflow",
	 "Backup versionati e protezione del documento.", 24017},
	{kVSDirectSettings, "direct-settings", "Direct Settings", "Sistema",
	 "Preferenze operative essenziali sempre accessibili.", 24018},
	{kVSSuiteCore, "suite-core", "Suite Core", "Sistema",
	 "Pannello, preferenze e coordinamento dei moduli.", 24019},
	{kVSProjectionStudio, "projection-studio", "Projection Studio", "Geometria",
	 "Linee, forme e solidi su griglia assonometrica.", 24020},
	{kVSFractalGrove, "fractal-grove", "Fractal Grove", "Geometria",
	 "Alberi vettoriali frattali con ramificazione parametrica.", 24024}
};

const VSToolDefinition kVSTools[kVSToolCount] = {
	{kVSToolSuiteCore, kVSSuiteCore, "Vector Suite Core", "Vector Suite", 24019},
	{kVSToolPrecisionPen, kVSPrecisionPen, "Vector Suite Precision Pen", "Precision Pen", 24000},
	{kVSToolFluidSketch, kVSFluidSketch, "Vector Suite Fluid Sketch", "Fluid Sketch", 24001},
	{kVSToolInkStudio, kVSInkStudio, "Vector Suite Ink Studio", "Ink Studio", 24002},
	{kVSToolWidthStudio, kVSWidthStudio, "Vector Suite Width Studio", "Width Studio", 24003},
	{kVSToolPathStudio, kVSPathStudio, "Vector Suite Path Studio", "Path Studio", 24004},
	{kVSToolGeometryLab, kVSGeometryLab, "Vector Suite Geometry Lab", "Geometry Lab", 24005},
	{kVSToolCollisionAlign, kVSCollisionAlign, "Vector Suite Collision Align", "Collision Align", 24006},
	{kVSToolMirrorStudio, kVSMirrorStudio, "Vector Suite Mirror Studio", "Mirror Studio", 24007},
	{kVSToolShapeReform, kVSShapeReform, "Vector Suite Shape Reform", "Shape Reform", 24008},
	{kVSToolLiveStyle, kVSLiveStyle, "Vector Suite Live Style", "Live Style", 24009},
	{kVSToolColorLab, kVSColorLab, "Vector Suite Color Lab", "Color Lab", 24010},
	{kVSToolTextureLab, kVSTextureLab, "Vector Suite Texture Lab", "Texture Lab", 24011},
	{kVSToolStippleLab, kVSStippleLab, "Vector Suite Stipple Lab", "Stipple Lab", 24012},
	{kVSToolRandomize, kVSRandomize, "Vector Suite Randomize", "Randomize", 24013},
	{kVSToolSmartFind, kVSSmartFind, "Vector Suite Smart Find", "Smart Find", 24014},
	{kVSToolVectorRepair, kVSVectorRepair, "Vector Suite Vector Repair", "Vector Repair", 24015},
	{kVSToolRasterLab, kVSRasterLab, "Vector Suite Raster Lab", "Raster Lab", 24016},
	{kVSToolAutoSave, kVSAutoSave, "Vector Suite Auto Save", "Auto Save", 24017},
	{kVSToolDirectSettings, kVSDirectSettings, "Vector Suite Direct Settings", "Direct Settings", 24018},
	{kVSToolProjectionLine, kVSProjectionStudio, "Vector Suite Projection Line", "Linea assonometrica", 24020},
	{kVSToolProjectionRectangle, kVSProjectionStudio, "Vector Suite Projection Rectangle", "Rettangolo proiettato", 24021},
	{kVSToolProjectionEllipse, kVSProjectionStudio, "Vector Suite Projection Ellipse", "Ellisse proiettata", 24022},
	{kVSToolProjectionBox, kVSProjectionStudio, "Vector Suite Projection Box", "Box isometrico", 24023},
	{kVSToolFractalGrove, kVSFractalGrove, "Vector Suite Fractal Grove", "Fractal Grove", 24024}
};
